name: "Winder"
board: "ESP32 Dev Controller V4"

# junction_deviation_mm: 0.01 .. 1

start:
  must_home: false
  deactivate_parking: true
  check_limits: true

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

uart2:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1

axes:
  shared_stepper_disable_pin: NO_PIN

  x:
    # (steps_per_mm * (max_rate_mm_per_min) / 60) = rate
    steps_per_mm: 400
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 460
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 500

    motor0:
      limit_all_pin: gpio.33
      # hard_limits: true
      hard_limits: false
      pulloff_mm: 1.000
      tmc_2209:
        uart_num: 2
        addr: 0
        r_sense_ohms: 0.110
        run_amps: 0.800
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        homing_amps: 0.250
        use_enable: false
        direction_pin: gpio.12
        step_pin: gpio.13
        disable_pin: gpio.14

    motor1:
      null_motor:

  y:
    # 16 pulses per step
    steps_per_mm: 1280.0
    max_rate_mm_per_min: 1000.0
    acceleration_mm_per_sec2: 1.25
    max_travel_mm: 10000000.000
    homing:
      # A value of -1 means the machine will not move, but the current machine position (mpos)
      # position of the axis will be set to the mpos_mm value for the axis.
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 100.000
      feed_mm_per_min: 100.000

    motor0:
      limit_all_pin: gpio.32:low
      hard_limits: false
      pulloff_mm: 0.3125
      standard_stepper:
        # Inverted direction
        direction_pin: gpio.26:low
        step_pin: gpio.25
        disable_pin: gpio.27

    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

i2c0:
   sda_pin: gpio.21
   scl_pin: gpio.22

oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 1000

macros:
  macro0: $SD/Run=f242-d64-l69.4-1550.gcode
  macro1: $SD/Run=f260-d64-l69.4-1550.gcode
  # Shift X & Y to start position
  # after_homing: G1X1.3Y-0.9F300
  after_homing: G1X2.2Y-0.9F300

control:
  reset_pin: NO_PIN
  feed_hold_pin: gpio.35
  cycle_start_pin: gpio.34
  macro0_pin: gpio.39
  macro1_pin: gpio.36
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN

status_outputs:
  report_interval_ms: 500
  run_pin: NO_PIN
  hold_pin: NO_PIN
  alarm_pin: NO_PIN
